const techIcons: Record<string, string> = {
  react: '/tech-icons/react.svg',
  'next.js': '/tech-icons/nextjs.svg',
  typescript: '/tech-icons/typescript.svg',
  javascript: '/tech-icons/javascript.svg',
  'tailwind css': '/tech-icons/tailwindcss.svg',
  'framer motion': '/tech-icons/framermotion.svg',
  html: '/tech-icons/html.svg',
  css: '/tech-icons/css.svg',
  vue: '/tech-icons/vue.svg',
  angular: '/tech-icons/angular.svg',
  svelte: '/tech-icons/svelte.svg',
  gsap: '/tech-icons/gsap.svg',
  'node.js': '/tech-icons/nodejs.svg',
  express: '/tech-icons/express.svg',
  postgresql: '/tech-icons/postgresql.svg',
  'payload cms': '/tech-icons/payloadcms.svg',
  'rest apis': '/tech-icons/restapi.svg',
  mongodb: '/tech-icons/mongodb.svg',
  graphql: '/tech-icons/graphql.svg',
  prisma: '/tech-icons/prisma.svg',
  firebase: '/tech-icons/firebase.svg',
  supabase: '/tech-icons/supabase.svg',
  python: '/tech-icons/python.svg',
  django: '/tech-icons/django.svg',
  'react native': '/tech-icons/reactnative.svg',
  expo: '/tech-icons/expo.svg',
  flutter: '/tech-icons/flutter.svg',
  swift: '/tech-icons/swift.svg',
  kotlin: '/tech-icons/kotlin.svg',
  git: '/tech-icons/git.svg',
  github: '/tech-icons/github.svg',
  figma: '/tech-icons/figma.svg',
  vercel: '/tech-icons/vercel.svg',
  docker: '/tech-icons/docker.svg',
  'vs code': '/tech-icons/vscode.svg',
  aws: '/tech-icons/aws.svg',
  linux: '/tech-icons/linux.svg',
  postman: '/tech-icons/postman.svg',
  npm: '/tech-icons/npm.svg',
  railway: '/tech-icons/railway.svg',
  paystack: '/tech-icons/paystack.svg',
  'claude code': '/tech-icons/claudecode.svg',
}

export function getTechIcon(name: string): string | null {
  return techIcons[name.toLowerCase()] || null
}
